name: 'Additional Test Setup'
description: 'Additional Test Setup for Ollama'
runs:
  using: "composite"
  steps:
    - name: Install Ollama and start server
      shell: bash
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh

    - name: Pull models in examples/
      shell: bash
      run: |
        ollama pull granite-code:8b
        ollama pull granite3-dense:8b
        ollama pull granite3.1-dense:8b
        ollama pull mxbai-embed-large

    - name: Wait for Ollama server
      shell: bash
      run: |
        sleep 10
        time curl -i http://localhost:11434