name: 'Ollama Setup'
description: 'Composte action to set up Run Examples'
inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.11'
  runner-os:
    description: 'Runner OS'
    required: true
  check:
    description: 'Files to patch tests/test_examples_run.yaml with. These are the PDL files that the test will run against. Defaults to all PDL files.'
    required: false
    default: ''
  head-ref:
    description: 'Head ref of the repo'
    required: true
runs:
  using: 'composite'
  steps:
    # Set up Ollama
    - uses: ./.github/actions/ollama

    # Configure Run Examples environment
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head-ref }}
    - name: Patch tests/test_examples_run.yaml with modified files
      if: ${{ inputs.check != '' }}
      uses: fjogeleit/yaml-update-action@main
      with:
        changes: |
          {
            "tests/test_examples_run.yaml": {
                "check": ${{ inputs.check }}
              }
          }
        commitChange: false
    - name: Print test Run Examples config
      shell: bash
      run: cat tests/test_examples_run.yaml

    # Run tests
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache pip
      uses: actions/cache@v4
      with:
        # This path is specific to Ubuntu
        path: ${{ env.pythonLocation }}
        # Look to see if there is a cache hit for the setup file
        key: ${{ inputs.runner-os }}-pip-new3-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ inputs.runner-os }}-pip-new3
          ${{ inputs.runner-os }}-new3
    - name: Install dependencies
      shell: bash
      run: pip install --upgrade --upgrade-strategy eager .[all]
    - name: Pip list packages
      shell: bash
      run: pip list
    - name: Show pip dependencies
      shell: bash
      run: |
        pip install pipdeptree
        pipdeptree -fl
    - name: Run tests
      shell: bash
      run: |
        cat tests/test_examples_run.yaml
        py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py --disable-pytest-warnings