---
name: Run examples

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  tests:
    name: Execution tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    # Run test on matrix
    - uses: ./.github/actions/ollama

    # Run tests
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v4
      with:
        # This path is specific to Ubuntu
        path: ${{ env.pythonLocation }}
        # Look to see if there is a cache hit for the setup file
        key: ${{ runner.os }}-pip-new3-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-new3
          ${{ runner.os }}-new3
    - name: Install dependencies
      shell: bash
      run: pip install --upgrade --upgrade-strategy eager .[all]
    - name: Pip list packages
      shell: bash
      run: pip list
    - name: Show pip dependencies
      shell: bash
      run: |
        pip install pipdeptree
        pipdeptree -fl
    - name: Run tests
      shell: bash
      env:
        WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
        WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
        WATSONX_URL: ${{ secrets.WATSONX_URL }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py --disable-pytest-warnings